# Generated by Django 4.2.11 on 2024-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/gallery/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_gallery',
            field=models.ManyToManyField(blank=True, to='store.productimage'),
        ),
    ]
