# Generated by Django 4.2.11 on 2024-03-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='iamge',
            new_name='image',
        ),
    ]
